### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by vincenzobaz** [vincenzobaz/DataViz-TrumpTweets#1]
- [ ] Select number of words for word usage OR load them all but set an initial zoom level (`visualizer.js`) #5
 - [x] retweets/stars bubbles (`visualizer.js`)
 - [x] position big div (HTML/CSS)
 - [x] Bubbles: click on group instead of circle (`bubbles.js`)
 - [x] Nice fonts / colors maybe look into bootstrap or already made frameworks (CSS)
 - [x] Animations/transitions for div erasure/appearance: css animations? (CSS)
 - [x] Title (HTML/js/CSS)
 - [x] instructions & subtitles (HTML/js/CSS) #4 
 - [x] Filter words displayed in word usage plot (`stats-tools.js`)
 - [x] Compare two topics / sentiments 
 - [x] Find one image per bubble and embed it #2
